info:
  description: this is bookstore deva config.
  url: https://github.com/lijianfx/config-repo
  foo: aa
spring:
  application:
    name: bookstore
  cloud:
    config:
      uri: ${SPRING_CONFIG_URI:http://localhost:8888}
