info:
  description:bookstore dev config
  url:https://github.com/lijianfx/config-repo
spring:
  application:
    name:bookstore
  cloud:
    config:
      uri:${SPRING_CONFIG_URI:http://localhost:8888}
